CREATE DATABASE EMPLEADOS_Join;

USE EMPLEADOS_Join;

CREATE TABLE PUESTO(NUM_PUESTO INT,
			NOMB VARCHAR(20),
			SUELDO_HORA INT,
			PRIMARY KEY (NUM_PUESTO));

CREATE TABLE DEPTO(NUM_DEPTO INT,
		      NOMB VARCHAR(20),
		      UBIC VARCHAR(30),
		      PRIMARY KEY(NUM_DEPTO));

CREATE TABLE EMPLEADO (NUM_EMP INT,
			   NOMB VARCHAR(20),
			   NUM_JEFE INT,
			   NUM_DEPTO INT,
			   NUM_PUESTO INT,
			   HORAS_CONTRATADAS INT,
			   EDAD INT,
			   PRIMARY KEY (NUM_EMP),
			   FOREIGN KEY (NUM_DEPTO)REFERENCES DEPTO(NUM_DEPTO),
			   FOREIGN KEY(NUM_PUESTO )REFERENCES PUESTO(NUM_PUESTO),
                       FOREIGN KEY(NUM_JEFE )REFERENCES EMPLEADO(NUM_EMP));
