use empleados_join;

SELECT *
      FROM  EMPLEADO JOIN DEPTO
      ON    EMPLEADO.NUM_DEPTO=DEPTO.NUM_DEPTO ;
      
SELECT *
      FROM  EMPLEADO JOIN DEPTO
      ON EMPLEADO.NUM_DEPTO=DEPTO.NUM_DEPTO
	  JOIN  PUESTO
	  ON   EMPLEADO.NUM_PUESTO=PUESTO.NUM_PUESTO;

SELECT EMPLEADO.NOMB, DEPTO.NOMB, PUESTO.NOMB
      FROM  EMPLEADO JOIN DEPTO
      ON EMPLEADO.NUM_DEPTO=DEPTO.NUM_DEPTO
	  JOIN  PUESTO
	  ON   EMPLEADO.NUM_PUESTO=PUESTO.NUM_PUESTO;

SELECT EMPLEADO.NOMB Empleado, DEPTO.NOMB Departamento, PUESTO.NOMB Puesto 
      FROM  EMPLEADO JOIN DEPTO
      ON EMPLEADO.NUM_DEPTO=DEPTO.NUM_DEPTO
	  JOIN  PUESTO
	  ON   EMPLEADO.NUM_PUESTO=PUESTO.NUM_PUESTO;